### ISSUE TITLE
Publishing Plot in PR Comments Not Working

### ISSUE THREAD

**Issue by Chapi15** [iterative/setup-cml#101]
I am trying to publish the confusion matrix in the comments section of a PR, it seems that there is a problem with the permissions of the runner:

`{"code":"ERR_INVALID_URL","input":"<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>cloudflare</center>\r\n</body>\r\n</html>\r\n","level":"error","message":"Invalid URL","stack":"TypeError [ERR_INVALID_URL]: Invalid URL\n    at new NodeError (node:internal/errors:405:5)\n    at new URL (node:internal/url:676:13)\n    at uriParam (/usr/local/lib/node_modules/@dvcorg/cml/src/utils.js:149:15)\n    at watermarkUri (/usr/local/lib/node_modules/@dvcorg/cml/src/utils.js:140:10)\n    at CML.publish (/usr/local/lib/node_modules/@dvcorg/cml/src/cml.js:351:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async visitor (/usr/local/lib/node_modules/@dvcorg/cml/src/cml.js:249:26)\n    at async Promise.all (index 0)\n    at async publishLocalFiles (/usr/local/lib/node_modules/@dvcorg/cml/src/cml.js:263:7)"}`

**Comment by Chapi15** [comment]
This command doesn't break the workflow: `cml comment create --pr --publish metrics.txt`. It crashes if I try to publish a markdown file
